name: Deploy teste
run-name: Deploy to dockerhub
on: [push]
jobs:
  Explore-GitHub-Action:
    runs-on: ubuntu-latest
    steps:
    - steps: 
      - name: Build image
        run: docker build -t fjoao9744/docker-teste:v3 .

      - name: Push image
        run: docker push fjoao9744/docker-teste:v3
