name: Deploy teste
run-name: Deploy to dockerhub
on: [push]
jobs:
  Explore-GitHub-Action:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: teste
        run:    echo "${{ secrets.DOCKER_USERNAME }}"

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build image
        run: docker build -t fjoao9744/docker-teste:v3 .

      - name: Push image
        run: docker push fjoao9744/docker-teste:v3
